### ISSUE TITLE
Is there any performance problem about every topic save as a dadger db?

### ISSUE THREAD

**Issue by bitcard** [redwood/redwood#85]
This is a great project for distributed APP.  I ran the chat demo,  found the data directory has two directory: chat.com_room-2837 and chat.com_room-2837_indices, it means  every topic save as a dadger db? if there are 100,000 rooms, maybe the APP create 100,000 DB instantces in memory? is there any config to avoid it? or any other solution for hundreds of rooms? thanks.

**Comment by brynbellomy** [comment]
Thanks for checking out the project. Yes, there are some limitations imposed by Badger. I believe I remember reading that there's a limit at around ~100 open Badger DBs before performance starts to degrade. We've been doing some work lately to consolidate some of the supporting DBs used by Redwood (peer store, tx store, key store, etc.), but so far, every state tree ("topic" in your message) has its own DB.

The reason for this is straightforward: when incoming updates to a state tree are being processed, Redwood needs to hold a Badger transaction open until the update is complete. If we put all of the state trees into a single DB, only one state tree can be updated at a time. For this reason, we've decided to separate them so that each tree can be updated in parallel, which hopefully improves performance/responsiveness.

This is a tricky balancing act, though, and I'm not sure it's going to work over the long term. It might make sense to make this more configurable, so that applications with many state trees (but fewer updates per second) can use a single DB. Applications with few state trees but many updates would be able to configure Redwood to use many DBs.

There also might be a more blended approach, where the system tries to intelligently consolidate a few state trees into each DB.

Anyway, curious to know if you have thoughts on this.

**Comment by bitcard** [comment]
> Thanks for checking out the project. Yes, there are some limitations imposed by Badger. I believe I remember reading that there's a limit at around ~100 open Badger DBs before performance starts to degrade. We've been doing some work lately to consolidate some of the supporting DBs used by Redwood (peer store, tx store, key store, etc.), but so far, every state tree ("topic" in your message) has its own DB.
> 
> The reason for this is straightforward: when incoming updates to a state tree are being processed, Redwood needs to hold a Badger transaction open until the update is complete. If we put all of the state trees into a single DB, only one state tree can be updated at a time. For this reason, we've decided to separate them so that each tree can be updated in parallel, which hopefully improves performance/responsiveness.
> 
> This is a tricky balancing act, though, and I'm not sure it's going to work over the long term. It might make sense to make this more configurable, so that applications with many state trees (but fewer updates per second) can use a single DB. Applications with few state trees but many updates would be able to configure Redwood to use many DBs.
> 
> There also might be a more blended approach, where the system tries to intelligently consolidate a few state trees into each DB.
> 
> Anyway, curious to know if you have thoughts on this.

Thanks for your reply, I ran the chat demo and chat in the room, so I think if develop a chatroom app based it, there will be many rooms, so worry about the performance.
